### ISSUE TITLE
Add favicon to page?

### ISSUE THREAD

**Issue by davidrosenberg** [davidrosenberg/ml2015#29]
I guess use the NYU one, which you can see here:
http://cs.nyu.edu/~dsontag/courses/ml14/
Unless anybody else has a more fun idea.

**Comment by domenic** [comment]
More fun ideas welcome. Also we could consider various higher-quality sizes for the various contexts in which the icon appears (e.g. pin to homescreen, or I think some bookmark UIs will use larger ones).

**Comment by domenic** [comment]
This site seems like a good way to generate the whole complement of icons http://realfavicongenerator.net/
