### ISSUE TITLE
Post the videos

### ISSUE THREAD

**Issue by davidrosenberg** [davidrosenberg/ml2015#32]
http://techtalks.tv/machine-learning-nyu-spring-2015/

**Comment by domenic** [comment]
@jandet thoughts on where to add these? Maybe retitle "Slides & Notes" to something more general and put links there?

**Comment by jandet-zz** [comment]
agreed on lumping it with notes using a different heading -- hmm what should it be called?

**Comment by domenic** [comment]
We could remove both the "References" and "Slides and Notes" headings entirely. Maybe even replace the pencil with some kind of video-related icon to make the videos primary.

**Comment by davidrosenberg** [comment]
What about just  making a little icon or link on the left side, maybe next to the words "LECTURE" and "LAB"  or under / next to the date or something?

**Comment by domenic** [comment]
Yeah that'd definitely work

**Comment by jandet-zz** [comment]
I like David's idea -- should I make this templated from the .yml?  Or some clever way to tell if they are posted yet?
