### ISSUE TITLE
Move office hours up to the top?

### ISSUE THREAD

**Issue by davidrosenberg** [davidrosenberg/ml2015#33]
Or just restyle it where they are now?

**Comment by domenic** [comment]
Moved them to the top. Can we kill the redundant "Schedule" section in About This Course? Maybe in combination with some kind of course calendar link in the header, per #9?

**Comment by domenic** [comment]
Also if you have a similar directions/map link for CDS common area that would be nice and symmetric.

**Comment by davidrosenberg** [comment]
Indeed: http://cds.nyu.edu/maps-and-directory/

**Comment by davidrosenberg** [comment]
Ok - I can do that (adding the CDS map)
