### ISSUE TITLE
Add in new textbook

### ISSUE THREAD

**Issue by davidrosenberg** [davidrosenberg/ml2015#38]
http://www-bcf.usc.edu/~gareth/ISL/

**Comment by domenic** [comment]
You need to fill in the blurb. Currently it reads 

> This book was only recently added to the course website and hasn't had a description written for it yet.

But otherwise should be good to go!

**Comment by domenic** [comment]
Finished in 5aaaf0fc6b171870c44eb7ac9bb93aab32e9222e.
